### ISSUE TITLE
Blind vias not handled

### ISSUE THREAD

**Issue by Xargas** [koendv/hyp2mat#10]
I tried to import a bigger PCB with hyp2mat into MATLAB.
This PCB contained blind vias on a six layer layout.
But after import, all vias are shown as vias from top to bottom.

For import I used these commands:
```
physical_constants;
f_max = 20e9;
pcbfile = 'Pcb.hyp';
CSX = InitCSX();
CSX = ImportHyperLynx(CSX, pcbfile);
FDTD = InitFDTD();
FDTD = SetGaussExcite(FDTD, f_max/2, f_max/2);
Sim_Path = 'tmp';
Sim_CSX = 'pcbcsx.xml';
WriteOpenEMS([Sim_Path '/' Sim_CSX], FDTD, CSX);
CSXGeomPlot([Sim_Path '/' Sim_CSX]);
```

I haven't found a documentation for the .hyp filetype, so I'm not sure how such blind vias are encoded in .hyp (I assume that they are supported. I assume that the "P" parameter from via line encodes this information.
(VIA X=2.421259 Y=4.192912 P=58)
(VIA X=2.577045 Y=5.495947 P=62)
(VIA X=2.588856 Y=5.464688 P=49)
Do you known more about this?

**Comment by koendv** [comment]
OK.

So the error is: blind vias were imported as through-hole vias. OK, I'll have a look.
Could you send me the complete .hyp file? Or, if the information is confidential, could you make a minimal board with the blind vias and the same number of layers? Maybe add a buried via?

On Feb 16, 2015, at 10:35 AM, Xargas <notifications@github.com> wrote:

> I assume that the "P" parameter from via line encodes this information.
> 
> (VIA X=2.421259 Y=4.192912 P=58)
> 

Yes, this is the via definition. The P= references a PADSTACK definition somewhere in the file. 

regards,

koen

**Comment by Xargas** [comment]
I created a repo with an example:
https://github.com/Xargas/hyp2matViaExample
I also added screenshots to make the via position clearer and a main.m for the import.

**Comment by koendv** [comment]
OK. That is sufficient data. Will try to fix this weekend.

regards,

koen

**Comment by koendv** [comment]
I've pushed some changes to the hyp2mat/stable github repository. 
If you're on linux using http://www.openems.de/index.php/Compile_from_Source, please update. 
If you're using windows, there's a new binary at http://www.kdvelectronics.eu/hyp2mat/hyp2mat-win32-current.zip . 

Does this solve the problems?

regards,

koen

**Comment by Xargas** [comment]
Yes, it looks very good with this version. I quick-tested the new build with the via example from above and with another PCB.

Regards,
Markus
