### ISSUE TITLE
HyperLynx Stackup - Metal copper thickness added to dielectric

### ISSUE THREAD

**Issue by Xargas** [koendv/hyp2mat#11]
Hallo!

When importing a HyperLynx file with hyp2mat, the copper thicknesses of signal layers get added to the dielectric thicknesses. But when a PCB is manufactured the thickness of the dielectric is not touched by this value.
So a more natural hyp2mat import should deliver the original thickness of the dielectrics.

Example:
Use ViaExample from https://github.com/Xargas/hyp2matViaExample, import via hyp2mat and view the generated pcb.m file (or view the value in the CSX structure).
For the first dielectric it generates a box:

```
CSX = AddBox(CSX, 'Dielectric_DE_GND2', 100, [ 0.04102, 0.09106, 0], [ 0.07709, 0.11163, 0.00028956]  );
```

where the height 0.00028956m is not the 0.254mm specified in the HyperLynx file, but 0.00028956m = 0.254mm+0.03556mm (dielectric plus copper).
_Is this addition done because of a special reason?_

Further, the copper layers only get imported as zero-thickness polygons. I did not find a commandline argument for this, but maybe it's inofficial.
_Is it possible to import the copper with the thickness of the stackup?_

So in overall with these questions: I think at the current import state, the simulated PCB results are always going to be to some degree different to the manufactured PCB.
_How do you see this?_

BR,
Markus

**Comment by koendv** [comment]
OK. Thanks for your feedback. 

1. Adding the thickness of the copper to the thickness of the dielectric:

This is an error. It will be fixed. 

Right now I'm implementing some changes in the export to csxcad;  I'll add a fix for the dielectric thickness at the same time. Sometime second half of this month.

2. Modeling copper in 3D:

Most people prefer simulation speed over accuracy. Simulation speed depends upon the number of points where the EM field has to be calculated. The number of points where the EM field has to be calculated depends upon the number of grid lines. The number of grid lines along a certain axis depend upon the smallest geometric feature along that axis. 

Along the vertical axis, a pcb has layers of dielectric alternating with layers of copper. Imagine a dual layer pcb; 18um of copper on 1.6 mm of dielectric.  If you model the copper as a 3D construct, each layer of copper gives you two grid lines on the z axis, spaced 18 um apart. If you simulate the copper using AddConductingSheet, each layer of copper gives you only a single grid line on the z-axis. Your grid lines will be spaced roughly 1.6 mm apart. 
From this I would guess simulating the copper as a 3D construct will be somewhere between 10 and 100 times slower than simulating the copper as a conducting sheet. 

An option to simulate the copper as 3D could be added; but a feature is only useful if people use it. Maybe the only use of simulating the copper as 3D would be to validate the correctness (or not) of simulating the copper as 2D. This might be of interest to other users.  Opinion?

3. So in overall with these questions: I think at the current import state, the simulated PCB results are always going to be to some degree different to the manufactured PCB. How do you see this?

If you simulate a PCB using a single simulator, you are certain. If you simulate a PCB using two different simulators, you begin to doubt.

koen

**Comment by Xargas** [comment]
2) *Most people prefer simulation speed over accuracy.* [...] *somewhere between 10 and 100 times slower*
I agree with that.

The reason I want to get the real dimensions is that I want to verify/fix some unwanted PCB behaviour whos origin is currently only partially known. So I wanted to start with the real model.
Simulation time is a reason, but when there are powerful simulation PCs, this increase in complexity can be handled.

3) I see your point. A lot of people will be ok with the zero thickness of the copper and get usable results e.g. for DDR interfaces, etc. But the small distances become critical when higher frequencies are viewed, as the elements cannot be neglected.

BR,
Markus

**Comment by koendv** [comment]
OK. I'll notify you when there's running code.

koen

**Comment by koendv** [comment]
OK. I've updated hyp2mat in the 'master' source tree. There's also a win32 binary for you at http://www.kdvelectronics.eu/hyp2mat/hyp2mat-win32-current.zip

hyp2mat default is simulating pcb copper as a 2D conductive sheet. A new option, 'metal-3d', creates a 3D model of the pcb copper instead. In your matlab script, just add 'metal-3d' to the ImportHyperLynx options, like this:
CSX = ImportHyperLynx(CSX, hypfilename, 'metal-3d', 'lossy-copper');

In the matlab directory you'll find a file "AddHyperlynxMetal3D.m". This file sets material properties, such as conductivity. You can add a customized copy of this file to your project if a simple resistive model is not sufficient.

Some rough numbers. Compared to the 2D conducting sheet model, in a 3D model of the copper:
- the number of grid lines along the vertical axis doubles. You can see this in AppCSXCD if you click on "2D", "yz".
- the number of timesteps is multiplied by 25.
- the simulation run takes 50 times longer.

If you want to simulate the skin effect in the 3d metal model, you need to have grid lines *inside* the metal as well, not just on the edges. Add these grid lines manually in your script.
The default 2D conductive sheet model already includes skin effect.

Interested in hearing how the 2D and 3D models compare.

regards,

koen
